# Generated by Django 4.1.4 on 2022-12-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='fd_source',
            field=models.CharField(choices=[('1', 'Contributions'), ('2', 'Earnings')], default='N', help_text='Indicates source of funds', max_length=1, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='gm_date_joined',
            field=models.DateTimeField(blank=True, help_text='Date member joined group', null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='gm_units',
            field=models.IntegerField(default=1, help_text='The number of units held', verbose_name='Units Held'),
        ),
        migrations.AddField(
            model_name='memberrecord',
            name='mr_units',
            field=models.IntegerField(default=1, help_text='The number of units held', verbose_name='Units Held'),
        ),
        migrations.AddField(
            model_name='period',
            name='pr_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The amount members are expected to contribute in the period', max_digits=15, verbose_name='Contribution Amount'),
        ),
        migrations.AddField(
            model_name='period',
            name='pr_due_date',
            field=models.DateTimeField(blank=True, help_text='Due Date', null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='advance',
            name='av_trans_date',
            field=models.DateTimeField(help_text='Transaction Date', verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='advancetrans',
            name='at_trans_date',
            field=models.DateTimeField(help_text='Transaction Date', verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fd_trans_date',
            field=models.DateTimeField(help_text='Transaction Date', verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='memberrecord',
            name='mr_trans_date',
            field=models.DateTimeField(help_text='Transaction Date', verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='period',
            name='pr_from_date',
            field=models.DateTimeField(blank=True, help_text='Starting Date', null=True, verbose_name='From Date'),
        ),
        migrations.AlterField(
            model_name='period',
            name='pr_to_date',
            field=models.DateTimeField(blank=True, help_text='Ending Date', null=True, verbose_name='To Date'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='rc_trans_date',
            field=models.DateTimeField(help_text='Transaction Date', verbose_name='Transaction Date'),
        ),
    ]
