# Generated by Django 4.1.4 on 2022-12-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starapp', '0002_fund_fd_source_groupmember_gm_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advance',
            options={'ordering': ['av_num'], 'verbose_name': 'Advance'},
        ),
        migrations.AlterModelOptions(
            name='advancetrans',
            options={'ordering': ['at_num'], 'verbose_name': 'Advance Transaction'},
        ),
        migrations.AlterModelOptions(
            name='fund',
            options={'ordering': ['fd_num'], 'verbose_name': 'Fund'},
        ),
        migrations.AlterModelOptions(
            name='groupmember',
            options={'ordering': ['gm_num'], 'verbose_name': 'Member'},
        ),
        migrations.AlterModelOptions(
            name='memberrecord',
            options={'ordering': ['mr_num'], 'verbose_name': 'Member Record'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['rc_num'], 'verbose_name': 'Receipt'},
        ),
    ]
