# Generated by Django 4.1.4 on 2023-01-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starapp', '0003_alter_advance_options_alter_advancetrans_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrecord',
            name='mr_category',
            field=models.CharField(choices=[('1', 'Contributions'), ('2', 'Advances')], default='1', help_text='Indicates the status of the transaction', max_length=1, verbose_name='Status'),
        ),
    ]
