# Generated by Django 4.1.4 on 2023-01-08 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starapp', '0004_memberrecord_mr_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='gm_address_1',
            field=models.CharField(blank=True, help_text='Member address 1', max_length=150, null=True, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='gm_address_2',
            field=models.CharField(blank=True, help_text='Member address 2', max_length=150, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='gm_address_3',
            field=models.CharField(blank=True, help_text='Member address 3', max_length=150, null=True, verbose_name='Address 3'),
        ),
        migrations.AlterField(
            model_name='memberrecord',
            name='mr_gm_num',
            field=models.ForeignKey(help_text='The member belongs', on_delete=django.db.models.deletion.CASCADE, related_name='member', to='starapp.groupmember', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='memberrecord',
            name='mr_pay_ref',
            field=models.CharField(help_text='The payment reference', max_length=20, verbose_name='Payment Ref'),
        ),
    ]
