# Generated by Django 4.1.4 on 2023-01-12 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starapp', '0005_alter_groupmember_gm_address_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='rc_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The balance on the advance', max_digits=15, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='advance',
            name='av_gm_num',
            field=models.ForeignKey(help_text='The member advanced money', on_delete=django.db.models.deletion.CASCADE, related_name='a_member', to='starapp.groupmember', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='advance',
            name='av_repay_plan',
            field=models.IntegerField(default=1, help_text='Repayment Plan', verbose_name='Repayment Plan'),
        ),
        migrations.AlterField(
            model_name='memberrecord',
            name='ad_date_a',
            field=models.DateTimeField(auto_now=True, help_text='Date record was last amended', null=True),
        ),
        migrations.AlterField(
            model_name='memberrecord',
            name='ad_date_c',
            field=models.DateTimeField(auto_now_add=True, help_text='Date record was created', null=True),
        ),
        migrations.AlterField(
            model_name='memberrecord',
            name='mr_category',
            field=models.CharField(choices=[('1', 'Contributions'), ('2', 'Advances'), ('3', 'Interest'), ('4', 'Penalties')], default='1', help_text='Indicates the status of the transaction', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='memberrecord',
            name='mr_pay_type',
            field=models.CharField(blank=True, choices=[('1', 'Cheque'), ('2', 'Transfer'), ('3', 'Cash'), ('4', 'Mobile Money')], default='N', help_text='Payment type', max_length=1, null=True, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='rc_processed',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Processed')], default='N', help_text='Indicates transaction has been processed', max_length=1, verbose_name='Processed'),
        ),
    ]
