# Generated by Django 4.1.4 on 2023-01-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starapp', '0007_blogpost_postcategory_postorigin_postcontribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='av_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Balance on the Advance', max_digits=15, verbose_name='Balance Amount'),
        ),
        migrations.AlterField(
            model_name='advance',
            name='av_status',
            field=models.CharField(choices=[('1', 'Applied'), ('2', 'Approved'), ('3', 'Declined'), ('4', 'Processed')], help_text='Indicates the status of the advance', max_length=1, verbose_name='Status'),
        ),
    ]
