# Generated by Django 4.1.4 on 2023-01-16 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starapp', '0008_advance_av_balance_alter_advance_av_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='av_gr_num',
            field=models.ForeignKey(default=1, help_text='The member s group', on_delete=django.db.models.deletion.CASCADE, related_name='a_group', to='starapp.grouptab', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='advance',
            name='av_processed',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Processed')], default='1', help_text='Indicates the processing status', max_length=1, verbose_name='Processed ?'),
        ),
    ]
